services:
  competitivebackend:
    image: ${DOCKER_REGISTRY-}competitivebackend
    build:
      context: .
      dockerfile: CompetitiveBackend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_persistent_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: maindb
      PGDATA: /data/postgres
    volumes:
        - database-data:/var/lib/postgresql/data
        - ./postgres/init:/docker-entrypoint-initdb.d/ 
    ports:
        - 5432:5432
    networks:
      - my_persistent_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/console_templates'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
    networks:
      - my_persistent_network
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATH_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_JSON_ENABLED=true
    volumes:
      - ./Benchmark/grafana/provisioning:/etc/grafana/provisioning
      - ./Benchmark/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - my_persistent_network
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   platform: linux/aarch64
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /dev/disk/:/dev/disk:ro
  #   privileged: true
  #   devices:
  #     - /dev/kmsg
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M
  #   networks:
  #     - my_persistent_network
  #   command:
  #   - --logtostderr=true 
  #   - --docker_only=true
  #   - --log_cadvisor_usage=false
  #   - --store_container_labels=true
  k6:
    image: grafana/k6:latest
    container_name: k6
    profiles: ["scenario1"]
    volumes:
      - ./Benchmark/Advanced/K6Scenarios:/scripts
      - ./k6-output:/output
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    command: run /scripts/scenarios/scenario1.js --out experimental-prometheus-rw
    ports:
       - 6565:6565
    networks:
      - my_persistent_network
    depends_on:
      - prometheus
      - competitivebackend
volumes:
  database-data:
  prometheus-data:
networks:
  my_persistent_network:
    driver: bridge
