services:
  competitivebackend:
    image: ${DOCKER_REGISTRY-}competitivebackend
    build:
      context: .
      dockerfile: CompetitiveBackend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_persistent_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: maindb
      PGDATA: /data/postgres
    volumes:
        - database-data:/var/lib/postgresql/data
        - ./postgres/init:/docker-entrypoint-initdb.d/ 
    ports:
        - 5432:5432
    networks:
      - my_persistent_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2g

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/console_templates'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=native-histograms'
    networks:
      - my_persistent_network
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATH_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_JSON_ENABLED=true
    volumes:
      - ./Benchmark/grafana/provisioning:/etc/grafana/provisioning
      - ./Benchmark/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - my_persistent_network
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata # The hostname Netdata will use
    ports:
      - 19999:19999 # Netdata web UI
    environment:
      - NETDATA_PROMETHEUS_WEB=yes
    cap_add:
      - SYS_PTRACE # Required for process monitoring
      - SYS_ADMIN # Required for various system metrics
    volumes:
      - /proc:/host/proc:ro # Mount /proc for process metrics
      - /sys:/host/sys:ro # Mount /sys for system metrics
      - /var/run/docker.sock:/var/run/docker.sock:ro # For Docker container monitoring
    networks:
      - my_persistent_network  # Добавьте это!
    restart: always
volumes:
  database-data:
  prometheus-data:
networks:
  my_persistent_network:
    driver: bridge
