services:
  competitivebackend:
    image: ${DOCKER_REGISTRY-}competitivebackend
    build:
      context: .
      dockerfile: CompetitiveBackend/Dockerfile
    depends_on:
      - postgres
    networks:
      - my_persistent_network
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: maindb
      PGDATA: /data/postgres
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/init:/docker-entrypoint-initdb.d/ 
    ports:
        - 5432:5432
    networks:
      - my_persistent_network
  adminer:
    image: adminer:4.8.1
    container_name: db_adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - my_persistent_network
  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    container_name: nginx_gateway
    ports:
      - "8080:80"  
    depends_on:
      - competitivebackend
      - adminer
    networks:
      - my_persistent_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
networks:
  my_persistent_network:
    driver: bridge
