services:
  competitivebackend:
    image: ${DOCKER_REGISTRY-}competitivebackend
    build:
      context: .
      dockerfile: CompetitiveBackend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Integration
      - TELEMETRY_OLTP_ADDRESS=http://otel-collector:4317
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - my_persistent_network
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: maindb
      PGDATA: /data/postgres
    volumes:
        - ./postgres/init:/docker-entrypoint-initdb.d/ 
    ports:
        - 5432:5432
    networks:
      - my_persistent_network
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config-integration.yml:/etc/otel/otel-collector-config.yml
      - ./otel-data:/data
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    networks:
      - my_persistent_network

networks:
  my_persistent_network:
    driver: bridge
