receivers:
  otlp:
    protocols:
      grpc:        # .NET OTLP gRPC
        endpoint: 0.0.0.0:4317
      http:        # запасной вариант для метрик/локального теста
        endpoint: 0.0.0.0:4318

exporters:
  # Prometheus metrics exporter
  prometheus:
    endpoint: "0.0.0.0:9464"

  # Debug exporter (замена deprecated "logging")
  debug:
    verbosity: detailed

  # Send traces to Jaeger via OTLP gRPC
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch: {}        # обязательный batching

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
