global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'competitivebackend'
    static_configs:
      - targets: ['competitivebackend:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  #- job_name: 'cadvisor'
  #  static_configs:
  #    - targets: ['cadvisor:8080']
  #  scrape_interval: 5s

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
    scrape_interval: 1s